# Generated by Django 5.2.12 on 2026-03-19 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', db_index=True, help_text='Given (first) name.', max_length=100)),
                ('surname', models.CharField(db_column='surname', db_index=True, help_text='Family name / surname.', max_length=100)),
                ('birth_date', models.DateField(blank=True, db_column='birth_date', db_index=True, help_text='Date of birth.', null=True)),
                ('identity_number', models.CharField(db_column='identity_number', help_text='Globally unique identity number.', max_length=50, unique=True)),
                ('father', models.ForeignKey(blank=True, db_column='father_id', help_text='Reference to the biological father.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_from_father', to='family_tree.person')),
                ('mother', models.ForeignKey(blank=True, db_column='mother_id', help_text='Reference to the biological mother.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_from_mother', to='family_tree.person')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'db_table': 'person',
                'managed': True,
                'indexes': [models.Index(fields=['father'], name='idx_person_father'), models.Index(fields=['mother'], name='idx_person_mother'), models.Index(fields=['surname'], name='idx_person_surname')],
            },
        ),
    ]
